// <auto-generated />
namespace SmartStore.CreditCardPay.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_PaymentMethodType_Field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_PaymentMethodType_Field));
        
        string IMigrationMetadata.Id
        {
            get { return "202203210147224_Add_PaymentMethodType_Field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
