// <auto-generated />
namespace SmartStore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class change_table_name_prefixSS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_table_name_prefixSS));
        
        string IMigrationMetadata.Id
        {
            get { return "202202280132583_change_table_name_prefixSS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
