// <auto-generated />
namespace CC.Plugins.Program.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ccProgram_UpdateField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ccProgram_UpdateField));
        
        string IMigrationMetadata.Id
        {
            get { return "202205291132120_ccProgram_UpdateField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
